CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    SALT VARCHAR(255) NOT NULL,
    PASSHASH VARCHAR(255) NOT NULL,
    IS_VERIFIED CHAR(1) NOT NULL,
    IS_ACTIVE CHAR(1) NOT NULL,
    JOINED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS GROUPS (
    GROUP_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    STARTED_BY INTEGER NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    TERM_LENGTH INTEGER NOT NULL,
    TERM_FREQUENCY VARCHAR(32) NOT NULL,
    TERM_AMOUNT INTEGER NOT NULL,
    MAX_PARTICIPANTS INTEGER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS INVITES (
    INVITE_ID SERIAL PRIMARY KEY,
    GROUP_ID INTEGER NOT NULL,
    INVITER_ID INTEGER NOT NULL,
    INVITED_EMAIL VARCHAR(255) NOT NULL,
    IS_ACCEPTED CHAR(1),
    INVITE_DATE TIMESTAMP NOT NULL,
    ACTED_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ACTIVE_GROUP_INFO (
    ACTIVE_GROUP_ID SERIAL PRIMARY KEY,
    GROUP_ID INTEGER NOT NULL,
    CURRENT_TERM INTEGER NOT NULL,
    PARTICIPANT_SIZE INTEGER NOT NULL,
    ACTIVATED_DATE TIMESTAMP NOT NULL
);